Lothric #8
luiznux/astora pull request #11
Opened 2019-08-04 17:02 UTC by luiznux

Modifiquei os arquivos e funções com o nome "linked_list" e também compilei para verificar se estava tudo funcionando e obtive o output  ``` 8/8 tests passed ``` .

2019-08-04 17:39 UTC, eaneto requested changes
- Makefile está com conflito.
- o arquivo bin/test_list não deveria existir por que é um binário
- Seria bom mudar o nome das funções para ter o prefixo `list_`, já que podemos ter funções com nomes iguais em partes diferentes do código.

2019-08-04 17:49 UTC, luiznux commented
Vou corrigir os erros.

2019-08-05 01:32 UTC, eaneto requested changes

2019-08-05 01:32 UTC, 3ldr0n commented on lothric/include/lib/list.h
> +// inicializa a lista
Esses comentários inline nas funções não são necessários já que temos as funções documentadas no .c

2019-08-05 01:35 UTC, luiznux commented on lothric/include/lib/list.h
> +// inicializa a lista
Acabei de notar, ja corrigi!

2019-08-05 01:35 UTC, merged